// ─────────────────────────────────────────────────────────────
// Normalized action types for the Approval Center
//
// Pure domain types — no transport or framework dependencies.
// These types bridge raw tool arguments to human-readable
// business diffs that SMB owners can understand.
// ─────────────────────────────────────────────────────────────

use serde::{Deserialize, Serialize};

/// Risk level derived from policy decision tier.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RiskLevel {
    Low,
    Medium,
    High,
    Critical,
}

impl std::fmt::Display for RiskLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Low => write!(f, "low"),
            Self::Medium => write!(f, "medium"),
            Self::High => write!(f, "high"),
            Self::Critical => write!(f, "critical"),
        }
    }
}

/// Human-readable business action summary.
///
/// Generated by the ActionNormalizer from raw tool arguments.
/// Displayed in the Approval Center UI.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NormalizedAction {
    /// Human-readable title, e.g. "Refund EUR 620.00 for order #1234"
    pub title: String,
    /// System target, e.g. "Shopify", "Google Calendar", "Stripe"
    pub system_target: String,
    /// Resource type, e.g. "order_refund", "calendar_event"
    pub resource_type: String,
    /// Optional resource identifier (e.g. order ID)
    pub resource_id: Option<String>,
    /// Before/after field changes for the business diff view.
    pub change_preview: Vec<BusinessDiffField>,
    /// Fields flagged as sensitive (highlighted in UI).
    pub sensitive_fields: Vec<String>,
    /// Whether this was normalized by a known adapter or is raw.
    pub change_preview_mode: String,
}

/// A single before/after field change in the business diff.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BusinessDiffField {
    /// Human-readable label, e.g. "Refund Amount"
    pub label: String,
    /// Previous value (None for create operations).
    pub before: Option<String>,
    /// New value (None for delete operations).
    pub after: Option<String>,
    /// Display format hint: "currency", "datetime", "text"
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
}

/// Enriched policy evaluation result for display in the Approval Center.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PolicyEvaluationDisplay {
    /// Decision variant: "allow", "deny", "require_approval", "require_proof"
    pub decision: String,
    /// Human-readable effect: "Action will proceed immediately", etc.
    pub effect: String,
    /// Approval tier if applicable: "tier0", "tier1", "tier2"
    pub tier: Option<String>,
    /// Which policy rule matched.
    pub policy_rule_id: String,
    /// Human-readable reason.
    pub reason: String,
    /// Proof type if required: "VerifiablePresentation"
    pub proof_type: Option<String>,
    /// Required claims for proof.
    pub required_claims: Vec<String>,
}

/// The full enriched approval payload persisted in KV and displayed
/// in the Approval Center.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActionReview {
    /// Unique approval request ID.
    pub approval_id: String,
    /// Correlates to the `ActionRequest.action_id`.
    pub action_id: String,
    /// Tenant scope.
    pub tenant_id: String,
    /// Where the action originated: "picoclaw", "ssi_agent", "webhook"
    pub source_type: String,
    /// The DID of the resource owner.
    pub owner_did: String,
    /// The DID that requested the action.
    pub requester_did: String,
    /// Fully qualified action name.
    pub action_name: String,
    /// Operation kind: "read", "create", "update", "delete", "transfer"
    pub operation_kind: String,
    /// Raw tool arguments (for technical details toggle).
    pub tool_args: serde_json::Value,
    /// Human-readable normalized action with business diff.
    pub normalized_action: NormalizedAction,
    /// Policy evaluation breakdown.
    pub policy_evaluation: PolicyEvaluationDisplay,
    /// Computed risk level.
    pub risk_level: RiskLevel,
    /// Current status.
    pub status: String,
    /// NATS reply subject for approval/denial.
    pub reply_subject: String,
    /// Timeout for approval decision.
    pub timeout_seconds: u64,
    /// Human-readable execution preview.
    pub execution_preview: String,
    /// Optional proof request details.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub proof_request: Option<serde_json::Value>,
    /// Who approved this request.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub approved_by: Option<String>,
    /// When the review was created.
    pub created_at: String,
    /// Last update timestamp.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}
